version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "[%(asctime)s] %(levelname)-8s: %(message)s"
    datefmt: "%Y%m%d %H:%M:%S"
  debug:
    format: "[%(asctime)s] %(levelname)-8s:(%(funcName)s) %(message)s"
    datefmt: "%Y%m%d %H:%M:%S"

root:
  level: DEBUG
  handlers: [console, file]

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: cli_app.utils.log.SetLogDirRotatingFileHandler
    level: DEBUG
    formatter: debug
    filename: app.log
    maxBytes: 20971520
    backupCount: 5
    logBaseDir: /var/log/cli-app
